filter:
  paths: [src/*]
  excluded_paths: [vendor/*, tests/*]
checks:
  php:
      code_rating: true
tools:
  external_code_coverage:
    timeout: 600
  php_analyzer: true
  php_changetracking: true
  php_code_sniffer:
    config:
        standard: "PSR2"
  php_cpd:
    enabled: true
    excluded_dirs: [vendor, tests]
  php_loc:
    enabled: true
    excluded_dirs: [vendor, tests]
  php_mess_detector: true
  php_pdepend: true
  sensiolabs_security_checker: true
