language: php
php:
  - 7.0
before_script:
  - composer install --dev --prefer-dist
script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phing
notifications:
  email:
    recipients:
      - wescleymatos@gmail.com
    on_success: always
