App\Domain\Entities\Group:
  type: entity
  repositoryClass: App\Infraestructure\Repositories\GroupRepository
  table: groups
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
  oneToMany:
    users:
      targetEntity: App\Domain\Entities\User
      mappedBy: group
