App\Domain\Entities\User:
  type: entity
  repositoryClass: Infraestructure\Repositories\UserRepository
  table: users
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
    lastName:
      type: string
  oneToOne:
    group:
      targetEntity: App\Domain\Entities\Group
      mappedBy: group
      #cascade: ["persist"]
      joinColumn:
        name: group_id
        referencedColumnName: id
