Domain\Entities\User:
  type: entity
  repositoryClass: Infraestructure\Repositories\UserRepository
  table: users
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
    lastName:
      type: string